### ISSUE TITLE
Failed to packet ID 3

### ISSUE THREAD

**Issue by JerichoTorrent** [smashyalts/AntiCrasher#12]
```
[23:44:56] [Netty Epoll Server IO #0/WARN]: io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
[23:44:56] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.DecoderException: net.craftsupport.anticrasher.packetevents.api.exception.PacketProcessException: Failed to map the Packet ID 3 to a PacketType constant. Bound: SERVER, Connection state: HANDSHAKING, Server version: 1.21
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:114)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[23:44:56] [Netty Epoll Server IO #1/WARN]: Caused by: net.craftsupport.anticrasher.packetevents.api.exception.PacketProcessException: Failed to map the Packet ID 3 to a PacketType constant. Bound: SERVER, Connection state: HANDSHAKING, Server version: 1.21
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at AntiCrasher-1.5.0.jar//net.craftsupport.anticrasher.packetevents.api.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:89)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at AntiCrasher-1.5.0.jar//net.craftsupport.anticrasher.packetevents.api.event.PacketReceiveEvent.<init>(PacketReceiveEvent.java:32)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at AntiCrasher-1.5.0.jar//net.craftsupport.anticrasher.packetevents.api.event.simple.PacketHandshakeReceiveEvent.<init>(PacketHandshakeReceiveEvent.java:33)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at AntiCrasher-1.5.0.jar//net.craftsupport.anticrasher.packetevents.api.util.EventCreationUtil.createReceiveEvent(EventCreationUtil.java:32)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at AntiCrasher-1.5.0.jar//net.craftsupport.anticrasher.packetevents.api.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:81)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at AntiCrasher-1.5.0.jar//net.craftsupport.anticrasher.packetevents.impl.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at AntiCrasher-1.5.0.jar//net.craftsupport.anticrasher.packetevents.impl.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at AntiCrasher-1.5.0.jar//net.craftsupport.anticrasher.packetevents.impl.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[23:44:56] [Netty Epoll Server IO #1/WARN]: 	... 41 more
```

**Comment by WolfPack206567** [comment]
report this into his discord server 
discord link: https://discord.gg/FJ3EVbA25d

**Comment by Skullians** [comment]
Resolved in newer versions that shade newer versions of packetevents
